# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# Test against these versions of Node.js.
environment:
  matrix:
    # Node.js
    - nodejs_version: "0.10"
    - nodejs_version: "0.11"
    # io.js
    - nodejs_version: "1.0"

matrix:
  allow_failures:
    # io.js 1.0.3 has a broken npm version included
    # and it's not possible to update it easily because of that
    # TODO remove it when io.js 1.0.4 comes to AppVeyor
    - nodejs_version: "1.0"

# Install scripts. (runs after repo cloning)
install:
  # Get the Node version with matching major & minor numbers
#  - ps: Install-Product node $env:nodejs_version
  # io.js 1.0.3 has a broken npm version included
  - ps: |
      If ($env:nodejs_version.StartsWith('1.0')) {
        Update-NodeJsInstallation 1.0.4
      } Else {
        Install-Product node $env:nodejs_version
      }
  # Log HTTP requests
  - npm config set loglevel http
  # Typical npm stuff.
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
